			
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports left_switch]
set_property IOSTANDARD LVCMOS33 [get_ports right_switch]
set_property IOSTANDARD LVCMOS33 [get_ports up_switch]
set_property IOSTANDARD LVCMOS33 [get_ports center_switch]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports left_switch]					
set_property PACKAGE_PIN W5 [get_ports clk]	
set_property PACKAGE_PIN T17 [get_ports right_switch]					
set_property PACKAGE_PIN T18 [get_ports up_switch]						
set_property PACKAGE_PIN U18 [get_ports center_switch]					
set_property PACKAGE_PIN U17 [get_ports reset]				
set_property PACKAGE_PIN P19 [get_ports h_sync]						

set_property PACKAGE_PIN R19 [get_ports v_sync]						

set_property PACKAGE_PIN G19 [get_ports {red[0]}]				
set_property PACKAGE_PIN H19 [get_ports {red[1]}]				
set_property PACKAGE_PIN J19 [get_ports {red[2]}]				

set_property PACKAGE_PIN N19 [get_ports {red[3]}]				

set_property PACKAGE_PIN J17 [get_ports {green[0]}]			
set_property PACKAGE_PIN H17 [get_ports {green[1]}]			
set_property PACKAGE_PIN G17 [get_ports {green[2]}]			
set_property PACKAGE_PIN D17 [get_ports {green[3]}]			

set_property PACKAGE_PIN N18 [get_ports {blue[0]}]			
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]			
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]			
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]			

## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]